sudo: required
dist: trusty

language: cpp

compiler:
  - gcc
  - clang
  
os:
  - linux
  - osx

env:
  - TRAVIS_BUILD_TYPE=Debug
  - TRAVIS_BUILD_TYPE=Release
  
before_install:
  # on os x use homebrew to install the dependencies 
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/x11; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/science; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; sudo apt-get update -qq; fi

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install yarp --only-dependencies; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install tinyxml; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; sudo apt-get install -y cmake libtinyxml-dev liblua5.1-dev python-dev ruby-dev libace-dev libgsl0-dev; fi

before_script:
  - cd ..
  # install yarp
  - git clone https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake -DCREATE_LIB_MATH:BOOL=ON -DCREATE_SHARED_LIBRARY:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE}  ..
  - make
  - sudo make install
  - sudo ldconfig
  - cd ../..
  
  - cd robot-testing
  # configure robot-testing framework
  - mkdir build 
  - cd build 
  - cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DENABLE_LUA_PLUGIN:BOOL=ON -DENABLE_PYTHON_PLUGIN:BOOL=ON -DENABLE_RUBY_PLUGIN:BOOL=ON -DENABLE_WEB_LISTENER:BOOL=ON -DENABLE_MIDDLEWARE_PLUGINS:BOOL=ON ..
  
script: 
  - make
  # test install/uninstall
  - sudo make install

notifications:
  email:
    - pegua1@gmail.com
